#!/bin/sh

set -e

rm -rf coverage

count=1;
for file in $(find t -name \*.t.js); do
  if [ "$file" != "t/register/run.t.js" ]; then
    node_modules/.bin/istanbul cover -x 't/**' $file
    mv coverage/coverage.json coverage/coverage$count.json
    count=$(expr $count + 1)
  fi
done

node_modules/.bin/istanbul report --root coverage --dir coverage > /dev/null

sed -i -e s,'^SF:'`pwd`/,SF:, coverage/lcov.info

exit 0
